[tool.coverage.run]
concurrency = ["multiprocessing"]

[tool.isort]
profile = "black"
src_paths = ["inboard", "tests"]

[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_defs = true
explicit_package_bases = true
files = ["**/*.py"]
namespace_packages = true
plugins = ["pydantic.mypy"]
show_error_codes = true

[tool.poetry]
name = "inboard"
version = "0.10.1"
description = "Docker images and utilities to power your Python APIs and help you ship faster."
authors = ["Brendon Smith <bws@bws.bio>"]
license = "MIT"
homepage = "https://github.com/br3ndonland/inboard"
repository = "https://github.com/br3ndonland/inboard"
documentation = "https://inboard.bws.bio"
readme = "README.md"
include = ["inboard/py.typed"]
keywords = ["asgi", "docker", "fastapi", "gunicorn", "uvicorn"]
classifiers = [
  "Natural Language :: English",
  "Topic :: Internet :: Log Analysis",
  "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
  "Topic :: Internet :: WWW/HTTP :: WSGI",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
  "Topic :: System :: Software Distribution",
  "Topic :: Utilities",
  "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.8"
gunicorn = "^20"
uvicorn = {version = "^0.13", extras = ["standard"]}
fastapi = {version = "^0.65.2", optional = true}
mkdocs-material = {version = "^7", optional = true}
starlette = {version = "^0.14", optional = true}
toml = {version = ">=0.10", optional = true}

[tool.poetry.dev-dependencies]
black = {version = "21.5b1", allow-prereleases = true}
flake8 = "^3.8"
isort = "^5.6"
mypy = "0.900"
pre-commit = "^2.8"
pytest = "^6.2"
pytest-cov = "^2.10"
pytest-mock = "^3.3"
pytest-timeout = "^1.4"
requests = "^2.24"
types-toml = "^0"

[tool.poetry.extras]
all = ["fastapi", "mkdocs-material", "toml"]
docs = ["mkdocs-material"]
fastapi = ["fastapi", "toml"]
starlette = ["starlette"]

[tool.poetry.urls]
Docker = "https://github.com/users/br3ndonland/packages/container/package/inboard"

[tool.pytest.ini_options]
addopts = "--cov=inboard -q"
minversion = "6.0"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
